# -*- coding: utf-8 -*-
"""Chunk size calculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKoPyU2Vuf6XKSD8efk0UIv7lxB14ixy
"""

!pip install langchain langchain-community

from langchain.document_loaders import CSVLoader
import pandas as pd
import numpy as np
import re

from google.colab import drive
drive.mount('/content/drive')

path="/content/tpp_Data_in_769audio_vn.csv"
df=pd.read_csv(filepath_or_buffer=path)
#Tổng số chữ
count=0
rows=0
for i in df['Chi tiết']:
    rows+=1
    count+=len(i)


#Trung bình số chữ mỗi ô của cột CT
c=count/rows
print(f'Trung bình mỗi ô cột Chi tiết {c}')

import re
tongCau=0
for i in df['Chi tiết']:
    sentences = re.split(r'[.\n\n\n]',i)
    l=len([s for s in sentences if s.strip()])
    tongCau+=l
c=count/tongCau
print(f'Trung bình số kí tự mỗi câu cột Chi tiết {c}')

count=0
rows=0
for i in df['Giới thiệu']:
    rows+=1
    count+=len(i)


#Trung bình số chữ mỗi ô của cột CT
c=count/rows
print(f'Trung bình mỗi ô cột Giới thiệu {c}')

import re
tongCau=0
for i in df['Giới thiệu']:
    sentences = re.split(r'[.\n\n\n]',i)
    l=len([s for s in sentences if s.strip()])
    tongCau+=l
c=count/tongCau
print(f'Trung bình số kí tự mỗi câu cột Giới thiệu {c}')

loader=CSVLoader(file_path=path, encoding="utf-8", csv_args={'delimiter': ','})

data = loader.load()

print(data[0].page_content)

print(len(data[0].page_content))

count=0
sum=0
for dt in data:
    sum+=len(dt.page_content)
    count+=1

print(f'Số kí tự trung bình mỗi dòng {sum/count}')

for i in (0,5):
  print(data[i].page_content)
  print('\n')