# -*- coding: utf-8 -*-
"""Data Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148nOdHIfkQeXkwffxLmNwsPfaoBtz-ei
"""

from google.colab import drive
drive.mount("/content/drive")

import pandas as pd

# column_names = ["Tên","link sản phẩm","Công Suất","Giá","Link ảnh","Tình trang","Mô tả","Giới thiệu","Chi tiết","Tập link ảnh"]
df = pd.read_csv("/content/drive/My Drive/Data_in_769audio_vn.csv", on_bad_lines='skip')

print(df.shape)



df = df.drop(columns=["Công Suất", "Mô tả"], axis=1)
df.head(1)

# Function to convert price to a numeric type
def clean_currency(price):
    if isinstance(price, str):  # Check if the input is a string
        # Remove the currency symbol and any trailing whitespace
        cleaned_str = price.replace('đ', '').strip()
        # Remove dots used as thousand separators
        cleaned_str = cleaned_str.replace('.', '')
        # Convert to integer
        return int(cleaned_str)
    elif np.isnan(price):
        # Return NaN as is or consider filling it with a default value like -1 or 0
        return np.nan
    else:
        # If it’s already a number, just return it as int
        return int(price)

import numpy as np

# Apply the function to the 'Giá' column
df['Giá'] = df['Giá'].apply(clean_currency).astype('float').astype('Int64')

# Check the cleaned and converted data
(df["Giá"][0:5])

def convert_status(status):
    if status is None:
        return None  # or handle None differently if needed
    elif status.lower() == 'còn hàng':
        return 1
    elif status.lower() == 'hết hàng' or status == "Status label not found on the page.":
        return 0
    else:
        return None  # or any other value that makes sense in your context

df['Tình trang'] = df['Tình trang'].astype('str')

# Applying the function to the 'Status' column
df['Tình trang'] = df['Tình trang'].apply(convert_status)

df.head()

df['Giới thiệu'] = df['Giới thiệu'].astype('str')
df['Chi tiết'] = df['Chi tiết'].astype('str')

import re

# Function to clean and format text
def format_text(text):
    # Normalize new lines, replacing multiple new lines with a single new line
    text = re.sub(r'\n\s*\n', '\n', text.strip())

    # Normalize whitespace within lines
    text = re.sub(r'[ \t]+', ' ', text)
    # Capitalize the first letter of each sentence in each paragraph separately
    paragraphs = text.split('\n')
    formatted_paragraphs = []
    for paragraph in paragraphs:
        sentences = re.split(r'(?<=[.!?]) +', paragraph.strip())
        formatted_sentences = [sentence.capitalize() for sentence in sentences]
        formatted_paragraph = '. '.join(formatted_sentences)
        formatted_paragraphs.append(formatted_paragraph)
    # Rejoin paragraphs with a single newline
    text = '\n'.join(formatted_paragraphs)
    # Ensure proper spacing after punctuations
    text = re.sub(r'\s([,.])', r'\1', text)
    text = re.sub(r'([,.])([^\s])', r'\1 \2', text)
    return text

new_df = df.copy()

# Apply formatting function
new_df['Giới thiệu'] = new_df['Giới thiệu'].apply(format_text)
new_df['Chi tiết'] = new_df['Chi tiết'].apply(format_text)

new_df["Chi tiết"][0]

new_df.head()

print(new_df.shape)
print(new_df.head())

# Define the path where the CSV will be saved
csv_file_path = "/content/drive/My Drive/tpp_Data_in_769audio_vn.csv"

# Save the DataFrame to a CSV file
new_df.to_csv(csv_file_path, index=False)

from google.colab import drive
drive.mount("/content/drive")

import pandas as pd

# column_names = ["Tên","link sản phẩm","Công Suất","Giá","Link ảnh","Tình trang","Mô tả","Giới thiệu","Chi tiết","Tập link ảnh"]

df = pd.read_csv("/content/drive/My Drive/Data_in_769audio_vn.csv", on_bad_lines='skip')

print(df.shape)

df.rename(columns={'Tình trang': 'Tình trạng', 'old_column_name2': 'new_column_name2'}, inplace=True)